---
- name: "Create {{ extension.name }} json file"
  ansible.builtin.copy:
    content: '{ "external_update_url": "https://clients2.google.com/service/update2/crx" }'
    dest: "/opt/google/chrome/extensions/{{ extension.id }}.json"
    owner: root
    group: root
    mode: 0644
  become: true