---
- name: Stop google chrome role when not correct architecture
  ansible.builtin.meta: end_role
  when: ansible_facts.architecture not in ['amd64', 'x86_64']

- name: Check google chrome is installed
  ansible.builtin.command: dpkg -s google-chrome-stable
  register: chrome_installed
  changed_when: false
  failed_when: false

- name: Install google chrome via .deb package
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present
  when: chrome_installed.rc != 0
