---
- name: Check google chrome is installed
  ansible.builtin.shell:
    cmd: dpkg -s google-chrome-stable
  register: chrome_installed
  changed_when: false
  failed_when: false

- name: Install google chrome via .deb package
  ansible.builtin.apt:
    deb: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    state: present
  when:
    - chrome_installed.rc != 0
    - ansible_facts.architecture in ['amd64', 'x86_64']
