---
- name: Setup apt
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: apt
      vars:
        setup_file: "{{ apt.setup_file }}"
        packages: "{{ apt.packages }}"

#- name: Setup github-cli
#  hosts: local
#  roles:
#    - role: gh
#
#- name: Setup sudo
#  hosts: local
#  roles:
#    - role: sudo
#      vars:
#        sudo_user: "{{ user.name }}"
#
#- name: Setup nvidia
#  hosts: local
#  roles:
#    - role: nvidia
#      vars:
#        deb_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
#
#- name: Setup vscode
#  hosts: local
#  roles:
#    - role: vscode
#
