---
- name: Initial setup
  hosts: local
  tags: init_setup
  become: true
  roles:
    - role: init
      tags: init
    - role: apt
      tags: apt
      vars:
        initial_upgrade_file: "{{ apt.intial_upgrade_file }}"
        packages: "{{ apt.standalone_packages }}"
    - role: user
      tags: user

- name: System setup
  hosts: local
  tags: system_setup
  become: true
  roles:
    - role: nvidia
      tags: nvidia
    - role: gnome
      tags: gnome
      become: false

- name: Software setup
  hosts: local
  tags: software_setup
  become: true
  roles:
    - role: vscode
      tags: vscode
      vars:
        extensions: "{{ vscode.extensions }}"
    - role: chrome
      tags: chrome
    - role: docker
      tags: docker
    - role: git
      tags: git
      vars:
        repos_dir: "{{ git.repos_dir }}"
        mmm_repo: "{{ git.mmm_repo }}"
        system_user_name: "{{ git.system.user.name }}"
        system_user_email: "{{ git.system.user.email }}"
        global_user_name: "{{ git.global.user.name }}"
        global_user_email: "{{ git.global.user.email }}"
