---
- name: Initial setup
  hosts: local
  become: true
  roles:
    - role: init
    - role: apt
      vars:
        initial_upgrade_file: "{{ apt.intial_upgrade_file }}"
    - role: user
      vars:
        main_user: "{{ user_main }}"

- name: System setup
  hosts: local
  become: true
  roles:
    - role: nvidia

#- name: Setup nvidia
#  hosts: local
#  roles:
#    - role: nvidia
#      vars:
#        deb_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
#
#- name: Setup vscode
#  hosts: local
#  roles:
#    - role: vscode
