---
- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Manage user
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    groups: sudo
    append: true
