---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}"
  become: true

- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present
  become: true

- name: Manage user
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    groups: sudo
    append: true
  become: true
