---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}"
  become: true

- name: "Install packages {{ packages | join(', ') }}"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  become: true
