---
- name: Clear default sources.list file
  ansible.builtin.copy:
    content: ""
    dest: /etc/apt/sources.list

- name: Re-add base debian repo
  ansible.builtin.deb822_repository:
    name: debian
    types:
      - deb
      - deb-src
    uris: http://deb.debian.org/debian/
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
      - "{{ ansible_facts['distribution_release'] }}-updates"
    components: main contrib non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
  register: debian_repo

- name: Re-add base debian security repo
  ansible.builtin.deb822_repository:
    name: debian-sec
    types:
      - deb
      - deb-src
    uris: https://security.debian.org/debian-security
    suites: "{{ ansible_facts['distribution_release'] }}-security"
    components: main contrib non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
  register: debian_sec_repo

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: debian_repo.changed or debian_sec_repo.changed

- name: Install standalone packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Set initial apt upgrade
  ansible.builtin.file:
    path: "{{ initial_upgrade_file }}"
    state: touch
    modification_time: preserve
    access_time: preserve
  register: initial_apt_upgrade

- name: Upgrade system
  ansible.builtin.apt:
    upgrade: true
  when: initial_apt_upgrade.changed

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt