---
- name: Stop vscode role when not correct architecture
  ansible.builtin.meta: end_role
  when: ansible_facts.architecture not in ['amd64', 'x86_64']

- name: Check vscode is installed
  ansible.builtin.command: dpkg -s code
  register: code_installed
  changed_when: false
  failed_when: false

- name: Install vscode via .deb package
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    state: present
  when: code_installed.rc != 0
  become: true

- name: Install vscode extensions
  include_tasks: ./install_extension.yaml
  loop: "{{ extensions }}"
  loop_control:
    loop_var: extension

- name: Copy over settings
  ansible.builtin.copy:
    src: ./files/settings.json
    dest: "{{ ansible_facts.user_dir }}/.config/Code/User/settings.json"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: 0664
