---
- name: "Check {{ setting.key }}"
  ansible.builtin.command:
    cmd: "gsettings get {{ setting.schema }} {{ setting.key }}"
  register: check_gsetting
  changed_when: false

- name: "Set {{ setting.key }}"
  ansible.builtin.command:
    cmd: "gsettings set {{ setting.schema }} {{ setting.key }} {{ setting.value }}"
  when: check_gsetting.stdout != setting.value
  become: true
