---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}"
  become: true

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Create repos dir
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/{{ repos_dir }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"

- name: Check git system user name
  ansible.builtin.command:
    cmd: git config --system --get user.name
  register: system_user_name_check
  changed_when: false

- name: Check git system user email
  ansible.builtin.command:
    cmd: git config --system --get user.email
  register: system_user_email_check
  changed_when: false

- name: Check git global user name
  ansible.builtin.command:
    cmd: git config --global --get user.name
  register: global_user_name_check
  changed_when: false
  become: false

- name: Check git global user email
  ansible.builtin.command:
    cmd: git config --global --get user.email
  register: global_user_email_check
  changed_when: false
  become: false

- name: Set git system user name
  ansible.builtin.command:
    argv:
      - git
      - config
      - --system
      - user.name
      - "{{ system_user_name }}"
  when: system_user_name_check.stdout != system_user_name

- name: Set git system user email
  ansible.builtin.command:
    argv:
      - git
      - config
      - --system
      - user.email
      - "{{ system_user_email }}"
  when: system_user_email_check.stdout != system_user_email

- name: Set git global user name
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - user.name
      - "{{ global_user_name }}"
  when: global_user_name_check.stdout != global_user_name
  become: false

- name: Set git global user email
  ansible.builtin.command:
    argv:
      - git
      - config
      - --global
      - user.email
      - "{{ global_user_email }}"
  when: global_user_email_check.stdout != global_user_email
  become: false
