---
apt:
  intial_upgrade_file: /etc/.ansible_initial_apt_upgrade
  packages:
    - apt-transport-https
    - bash
    - curl
    - wget
    - git
    - gnome-keyring
    - gpg
    - gcc
    - make
    - sudo
    - python3
    - python3-pip
