---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ 60 * 60 * 12 }}"
  become: true

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - gnome-terminal
      - ca-certificates
      - curl
    state: present
  become: true

- name: Check docker is installed
  ansible.builtin.command: dpkg -s docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin 
  register: docker_check
  changed_when: false
  failed_when: false

- name: Setup docker repo
  block:
    - name: Create keyring file
      ansible.builtin.command: install -m 0755 -d /etc/apt/keyrings
    - name: Download docker key file
      ansible.builtin.command: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - name: Change key permissions
      ansible.builtin.command: chmod a+r /etc/apt/keyrings/docker.asc
    - name: Add docker repo
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_facts.distribution_release }}"
        components: stable
        signed_by: /etc/apt/keyrings/docker.asc
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
  when: docker_check.rc != 0
  become: true

- name: Install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: "Ensure user {{ ansible_facts.user_id }} is in docker group"
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    groups: docker
    append: true
  become: true

- name: Start docker service on boot
  ansible.builtin.service:
    name: docker
    enabled: true
  become: true

- name: Start containerd service on boot
  ansible.builtin.service:
    name: containerd
    enabled: true
  become: true
